# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChipTestMain.ui'
# Created by: PyQt5 UI code generator 5.15.2
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys

import cv2
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
import NewLine
from PyQt5.QtGui import *

class Ui_MainWindow(QtWidgets.QMainWindow):

    def __init__(self):
        super(Ui_MainWindow,self).__init__()
        self.setupUi(self)
        self.retranslateUi(self)

        #成员变量
        self.Threshold=127
        self.OrImgPath=''
        self.BinaryImgPath=''
        #self.OrImg=cv2.imread('../images/OrImg/M2.png')
        #self.BinaryImg=cv2.imread('../images/OrImg/M2.png')
        self.MaxThreshold=0
        self.MinThreshold=0
        self.DifferenceThreshold=0

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        # self.horizontalLayout.setObjectName("horizontalLayout")
        #
        # self.gridLayout = QtWidgets.QGridLayout()
        # self.gridLayout.setObjectName("gridLayout")

        self.Slider_Threshold = QtWidgets.QSlider(self.centralwidget)
        self.Slider_Threshold.setGeometry(QtCore.QRect(30, 120, 160, 22))
        self.Slider_Threshold.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Threshold.setMinimum(0)
        self.Slider_Threshold.setMaximum(255)
        self.Slider_Threshold.setValue(127)
        self.Slider_Threshold.setSingleStep(1)
        #self.Slider_Threshold.setTickInterval(5)
        #self.Slider_Threshold.setTickPosition(QSlider.TicksBelow)
        self.Slider_Threshold.setObjectName("Slider_Threshold")
        self.Slider_Threshold.valueChanged.connect(self.Threshold_change)
        #self.gridLayout.addWidget(self.Slider_Threshold, 30, 120, 160, 22)

        self.label_Threshold = QtWidgets.QLabel(self.centralwidget)
        self.label_Threshold.setGeometry(QtCore.QRect(30, 90, 71, 21))
        self.label_Threshold.setObjectName("label_Threshold")
        #self.gridLayout.addWidget(self.label_Threshold, 30, 90, 71, 21)

        self.label_showThreshold = QtWidgets.QLabel(self.centralwidget)
        self.label_showThreshold.setGeometry(QtCore.QRect(110, 90, 54, 20))
        self.label_showThreshold.setObjectName("label_showThreshold")
        #self.gridLayout.addWidget(self.label_showThreshold, 110, 90, 54, 20)

        self.label_OrImg = QtWidgets.QLabel(self.centralwidget)
        self.label_OrImg.setGeometry(QtCore.QRect(20, 210, 351, 291))
        self.label_OrImg.setObjectName("label_OrImg")
        #self.gridLayout.addWidget(self.label_OrImg, 20, 210, 351, 291)

        self.label_BinaryImg = QtWidgets.QLabel(self.centralwidget)
        self.label_BinaryImg.setGeometry(QtCore.QRect(420, 210, 351, 291))
        self.label_BinaryImg.setObjectName("label_BinaryImg")
        #self.gridLayout.addWidget(self.label_BinaryImg, 420, 210, 351, 291)

        self.Button_ReadImg = QtWidgets.QPushButton(self.centralwidget)
        self.Button_ReadImg.setGeometry(QtCore.QRect(20, 50, 75, 23))
        self.Button_ReadImg.setObjectName("Button_ReadImg")
        self.Button_ReadImg.clicked.connect(self.readImg)
        #self.gridLayout.addWidget(self.Button_ReadImg, 20, 50, 75, 23)

        self.lineEdit_BigT = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_BigT.setGeometry(QtCore.QRect(380, 40, 81, 20))
        self.lineEdit_BigT.setObjectName("lineEdit_BigT")
        #self.gridLayout.addWidget(self.lineEdit_BigT, 380, 40, 81, 20)

        self.label_BigT = QtWidgets.QLabel(self.centralwidget)
        self.label_BigT.setGeometry(QtCore.QRect(310, 40, 54, 12))
        self.label_BigT.setObjectName("label_BigT")
        #self.gridLayout.addWidget(self.label_BigT, 310, 40, 54, 12)

        self.lineEdit_SmallT = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_SmallT.setGeometry(QtCore.QRect(380, 80, 81, 20))
        self.lineEdit_SmallT.setObjectName("lineEdit_SmallT")
        #self.gridLayout.addWidget(self.lineEdit_SmallT, 380, 80, 81, 20)

        self.label_SmallT = QtWidgets.QLabel(self.centralwidget)
        self.label_SmallT.setGeometry(QtCore.QRect(310, 80, 54, 20))
        self.label_SmallT.setObjectName("label_SmallT")
        #self.gridLayout.addWidget(self.label_SmallT, 310, 80, 54, 20)

        self.label_DifferenceT = QtWidgets.QLabel(self.centralwidget)
        self.label_DifferenceT.setGeometry(QtCore.QRect(310, 120, 54, 20))
        self.label_DifferenceT.setObjectName("label_DifferenceT")
        #self.gridLayout.addWidget(self.label_DifferenceT, 310, 120, 54, 20)

        self.lineEdit_TDifference = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_TDifference.setGeometry(QtCore.QRect(380, 120, 81, 20))
        self.lineEdit_TDifference.setObjectName("lineEdit_TDifference")
        #self.gridLayout.addWidget(self.lineEdit_TDifference, 380, 120, 81, 20)

        self.Button_ConfirmProgress = QtWidgets.QPushButton(self.centralwidget)
        self.Button_ConfirmProgress.setGeometry(QtCore.QRect(560, 120, 75, 23))
        self.Button_ConfirmProgress.setObjectName("Button_ConfirmProgress")
        #self.gridLayout.addWidget(self.Button_ConfirmProgress, 560, 120, 75, 23)
        self.Button_ConfirmProgress.clicked.connect(self.binaryImg)



        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        #self.gridLayout.addWidget(self.menubar, 0, 0, 800, 23)

        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")

        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")

        MainWindow.setStatusBar(self.statusbar)
        self.actionBigSmall = QtWidgets.QAction(MainWindow)
        self.actionBigSmall.setObjectName("actionBigSmall")

        self.menu.addAction(self.actionBigSmall)
        self.menubar.addAction(self.menu.menuAction())

        # self.horizontalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Threshold.setText(_translate("MainWindow", "单阈值二值化"))
        self.label_showThreshold.setText(_translate("MainWindow", "127"))
        self.label_OrImg.setText(_translate("MainWindow", "Img"))
        self.label_BinaryImg.setText(_translate("MainWindow", "Binary"))
        self.Button_ReadImg.setText(_translate("MainWindow", "读取图片"))
        self.label_BigT.setText(_translate("MainWindow", "最大通道"))
        self.label_SmallT.setText(_translate("MainWindow", "最小通道"))
        self.label_DifferenceT.setText(_translate("MainWindow", "通道差值"))
        self.Button_ConfirmProgress.setText(_translate("MainWindow", "确定"))
        self.menu.setTitle(_translate("MainWindow", "开始"))
        self.actionBigSmall.setText(_translate("MainWindow", "BigSmall"))

    #槽函数
    def readImg(self):
        # 从C盘打开文件格式（*.jpg *.gif *.png *.jpeg）文件，返回路径
        image_file, _ = QFileDialog.getOpenFileName(self, 'Open file', 'E:\\Projects\\Items\\ChipTest\\images', 'Image files (*.jpg *.gif *.png *.jpeg)')
        # 缩放图片 设置标签的图片
        jpg = QtGui.QPixmap(image_file).scaled(self.label_OrImg.width(), self.label_OrImg.height())
        self.OrImgPath = image_file
        print(self.OrImgPath)
        print(self.label_OrImg.width(),self.label_OrImg.height())
        self.label_OrImg.setPixmap(jpg)

    def getThreshold(self):
        return self.Threshold

    def Threshold_change(self):
        self.Threshold=self.Slider_Threshold.value()
        self.label_showThreshold.setText(str(self.Threshold))
        print(self.Threshold)

    def binaryImg(self):
        img,binaryImgPath = NewLine.image_binarization(self.OrImgPath, self.Threshold)
        img = QtGui.QPixmap(binaryImgPath).scaled(self.label_BinaryImg.width(), self.label_BinaryImg.height())
        self.BinaryImgPath = binaryImgPath
        self.label_BinaryImg.setPixmap(img)

if __name__ == "__main__":
    App = QApplication(sys.argv)    # 创建QApplication对象，作为GUI主程序入口
    aw = Ui_MainWindow()            # 创建主窗体对象，实例化Ui_MainWindow
    w = QMainWindow()               # 实例化QMainWindow类
    aw.setupUi(w)                   # 主窗体对象调用setupUi方法，对QMainWindow对象进行设置
    w.show()                        # 显示主窗体
    sys.exit(App.exec_())           # 关闭窗口