# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'regionSplit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.lineEdit_diffCh = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_diffCh.setGeometry(QtCore.QRect(160, 160, 113, 20))
        self.lineEdit_diffCh.setObjectName("lineEdit_diffCh")
        self.label_diffCh = QtWidgets.QLabel(Dialog)
        self.label_diffCh.setGeometry(QtCore.QRect(50, 160, 81, 20))
        self.label_diffCh.setObjectName("label_diffCh")
        self.button_confirm = QtWidgets.QPushButton(Dialog)
        self.button_confirm.setGeometry(QtCore.QRect(200, 230, 75, 23))
        self.button_confirm.setObjectName("button_confirm")
        self.button_cancel = QtWidgets.QPushButton(Dialog)
        self.button_cancel.setGeometry(QtCore.QRect(290, 230, 75, 23))
        self.button_cancel.setObjectName("button_cancel")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(40, 40, 311, 91))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_diffCh.setText(_translate("Dialog", "通道差值"))
        self.button_confirm.setText(_translate("Dialog", "确定"))
        self.button_cancel.setText(_translate("Dialog", "取消"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">说明：通道差值法利用像素点最大通道值和最小通道值的差异性，对图层照片进行处理。默认参数选择30，可上下50%浮动进行调优。</p></body></html>"))
